import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Header */}
        <header>
          <nav className="flex">
            <Link href="/">Home</Link>
            <Link href="/contact-us">Contact Us</Link>
            <Link href="/about-us">About Us</Link>
            <Link href="/article">Article</Link>
            <Link href="/image-demo">Images</Link>
          </nav>
        </header>
        {children}
        {/* Footer */}
      </body>
    </html>
  );
}
